#!/bin/python

if __name__ == '__main__':
	a=[1,3,7,4,5,6]
	z = int(input('z ='))

	for x in range(len(a)):
		for y in range(len(a)):
			if z== a[x] + a[y]:
				print (f"tova sa chislata {a[x]} i {a[y]}")
					
				quit()
	print('Nqma takiva chisla')
